### ISSUE TITLE
Disable numeric answers?

### ISSUE THREAD

**Issue by JarkkoLinnanvirta** [silverstripe/silverstripe-mathspamprotection#19]
Some spam submissions come through. I guess it's quite easy for bots to make multiple submissions and randomize the answer in the field. Some times they get it correct. My form is in Finnish so they shouldn't be able to guess Finnish words :). I think it would be good to have an option if numeric aswers are accepted or not. I know how to disable them by hard coding, so I can deal with it in my form, but I don't know how to make it an option in the backend so I'm not creating an actual pull request.

**Comment by dhensby** [comment]
fixed by #30
