### ISSUE TITLE
What is the idea?

### ISSUE THREAD

**Issue by hhirsch** [silverstripe/silverstripe-mathspamprotection#25]
Hello,

I always wondered what the idea behind math anti-spam was.
Because the last time I checked computers were better at maths than humans.

Regards 
Henry

**Comment by dhensby** [comment]
The idea is to provide a simple barrier to unsophisticated spam bots whilst sparing the user the pain of very difficult or at least irritating CAPTCHAs. 

Its also much better for accessibility as screen readers are more easily able to read out a question to a user and the answer is much more simple to find out. 

Whilst this solution appears trivial to bypass, anechdotally, I can report that adding such trivial questions to forms that were being targeted reduces that spam to 0 and we haven't had spam instances after using it even after 2 years of a previously abused form.
