### ISSUE TITLE
Composer requirements force dev-master of silverstripe-spamprotection

### ISSUE THREAD

**Issue by muskie9** [silverstripe/silverstripe-mathspamprotection#45]
When trying to use a tagged version of `silverstripe-spamprotection` an error occurs.

**Comment by dhensby** [comment]
What's the error?

**Comment by muskie9** [comment]
I specified a tag for `silverstripe-spamprotection` in my project's `composer.json` file. I received an error for this module loading in as this module required `"silverstripe/spamprotection": "dev-master"` so it states the tag I specified doesn't match the required `dev-master` as set in this module's composer file, if that makes sense.

**Comment by dhensby** [comment]
ah, I think I see what you mean...

@tractorcow composer.json needs a proper version constraint, it seems

**Comment by muskie9** [comment]
I would've submitted a pr but didn't know what version would be appropriate.

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-mathspamprotection/pull/46
